# Generated by Django 5.0.1 on 2024-01-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrpition',
            new_name='description',
        ),
    ]
